import { EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle } from "discord.js";

const PAGES: { title: string; color: number; fields: string }[] = [
  {
    title: "⚙️ Setup Commands",
    color: 0x3498db,
    fields: [
      "`#setlog #channel` / `/setlog`",
      "↳ Set the mod-log channel for all moderation logs",
      "",
      "`#setwelcome #channel` / `/setwelcome`",
      "↳ Set the welcome channel for new member greetings",
      "",
      "`#setverify #channel @role` / `/setverify`",
      "↳ Set the verification channel and the role given after verifying",
      "",
      "`#setupverify` / `/setupverify`",
      "↳ Post the verification embed with the Verify button in the set channel",
    ].join("\n"),
  },
  {
    title: "🔨 Moderation — Bans & Kicks",
    color: 0xe74c3c,
    fields: [
      "`#ban @user [reason]` / `/ban`",
      "↳ Permanently ban a member from the server",
      "",
      "`#unban <userID> [reason]` / `/unban`",
      "↳ Unban a user by their Discord ID",
      "",
      "`#kick @user [reason]` / `/kick`",
      "↳ Kick a member from the server",
      "",
      "`#softban @user [reason]` / `/softban`",
      "↳ Ban + immediately unban to delete recent messages",
      "",
      "`#tempban @user <duration> [reason]` / `/tempban`",
      "↳ Ban a user for a set time — e.g. `1h`, `7d`",
      "",
      "`#massban <id1 id2 ...> [reason]` / `/massban`",
      "↳ Ban multiple users by ID at once",
      "",
      "`#hackban <userID> [reason]` / `/hackban`",
      "↳ Ban a user by ID even if they're not in the server",
    ].join("\n"),
  },
  {
    title: "🔨 Moderation — Mutes, Warns & Messages",
    color: 0xe67e22,
    fields: [
      "`#mute @user <duration> [reason]` / `/mute`",
      "↳ Timeout a user — e.g. `10m`, `2h`, `1d`",
      "",
      "`#unmute @user` / `/unmute`",
      "↳ Remove a timeout from a user",
      "",
      "`#warn @user <reason>` / `/warn`",
      "↳ Issue an official warning to a user",
      "",
      "`#warnings @user` / `/warnings`",
      "↳ View all warnings for a specific user",
      "",
      "`#clearwarn @user` / `/clearwarn`",
      "↳ Clear all warnings for a user",
      "",
      "`#warnlist` / `/warnlist`",
      "↳ List all users with active warnings in the server",
      "",
      "`#purge <amount>` / `/purge`",
      "↳ Bulk delete up to 100 messages in the current channel",
      "",
      "`#purgeuser @user <amount>` / `/purgeuser`",
      "↳ Delete messages from a specific user only",
      "",
      "`#purgebot <amount>` / `/purgebot`",
      "↳ Delete bot messages in bulk",
    ].join("\n"),
  },
  {
    title: "🔨 Moderation — Channels, Nicks & Notes",
    color: 0xf39c12,
    fields: [
      "`#lock [#channel]` / `/lock`",
      "↳ Lock a channel so members can't send messages",
      "",
      "`#unlock [#channel]` / `/unlock`",
      "↳ Unlock a channel so members can talk again",
      "",
      "`#lockdown` / `/lockdown`",
      "↳ Lock ALL channels at once (server lockdown)",
      "",
      "`#unlockdown` / `/unlockdown`",
      "↳ Unlock ALL channels and restore normal access",
      "",
      "`#slowmode <seconds> [#channel]` / `/slowmode`",
      "↳ Set slowmode — use `0` to disable",
      "",
      "`#nuke` / `/nuke`",
      "↳ Delete and recreate the current channel (wipes all messages)",
      "",
      "`#nick @user <nickname>` / `/nick`",
      "↳ Change a user's server nickname",
      "",
      "`#cleannick @user` / `/cleannick`",
      "↳ Reset a user's nickname back to their username",
      "",
      "`#dehoist @user` / `/dehoist`",
      "↳ Remove hoisting special characters from a user's nickname",
      "",
      "`#strip @user` / `/strip`",
      "↳ Remove ALL roles from a user at once",
      "",
      "`#note @user <text>` / `/note`",
      "↳ Add a private mod note to a user (not visible to them)",
      "",
      "`#notes @user` / `/notes`",
      "↳ View all mod notes for a user",
      "",
      "`#clearnotes @user` / `/clearnotes`",
      "↳ Delete all mod notes for a user",
      "",
      "`#history @user` / `/history`",
      "↳ View a user's full moderation history",
    ].join("\n"),
  },
  {
    title: "🎤 Voice Commands",
    color: 0x9b59b6,
    fields: [
      "`#move @user #vc-channel` / `/move`",
      "↳ Move a user to a different voice channel",
      "",
      "`#vckick @user` / `/vckick`",
      "↳ Disconnect a user from their voice channel",
      "",
      "`#vcmute @user` / `/vcmute`",
      "↳ Server-mute a user in voice (they can't speak)",
      "",
      "`#vcunmute @user` / `/vcunmute`",
      "↳ Remove server-mute from a user in voice",
      "",
      "`#deafen @user` / `/deafen`",
      "↳ Server-deafen a user (they can't hear others)",
      "",
      "`#undeafen @user` / `/undeafen`",
      "↳ Remove server-deafen from a user",
      "",
      "`#massdeafen @u1 @u2 ...` / `/massdeafen`",
      "↳ Deafen multiple users in voice at once",
      "",
      "`#massundeafen @u1 @u2 ...` / `/massundeafen`",
      "↳ Undeafen multiple users in voice at once",
      "",
      "`#vcban @user` / `/vcban`",
      "↳ Prevent a user from joining any voice channel",
      "",
      "`#unvcban @user` / `/unvcban`",
      "↳ Restore a user's access to voice channels",
    ].join("\n"),
  },
  {
    title: "🏷️ Roles & Channels",
    color: 0x2ecc71,
    fields: [
      "`#addrole @user @role` / `/addrole`",
      "↳ Give a role to a user",
      "",
      "`#removerole @user @role` / `/removerole`",
      "↳ Remove a role from a user",
      "",
      "`#createrole <name> [#color]` / `/createrole`",
      "↳ Create a new server role",
      "",
      "`#deleterole @role` / `/deleterole`",
      "↳ Delete a role from the server",
      "",
      "`#setcolor @role #hex` / `/setcolor`",
      "↳ Change a role's color — e.g. `#FF5733`",
      "",
      "`#mentionable @role` / `/mentionable`",
      "↳ Toggle whether a role can be @mentioned by anyone",
      "",
      "`#roledump @role` / `/roledump`",
      "↳ List all members who have a specific role",
      "",
      "`#createchannel <name> [text|voice]` / `/createchannel`",
      "↳ Create a new text or voice channel",
      "",
      "`#deletechannel #channel` / `/deletechannel`",
      "↳ Delete a channel permanently",
      "",
      "`#invites` / `/invites`",
      "↳ List all active invite links in the server",
      "",
      "`#clearinvites` / `/clearinvites`",
      "↳ Delete all server invite links at once",
      "",
      "`#createinvite [#channel]` / `/createinvite`",
      "↳ Generate a new permanent invite link",
    ].join("\n"),
  },
  {
    title: "💬 Communication & ℹ️ Info",
    color: 0x1abc9c,
    fields: [
      "`#say <message> [#channel]` / `/say`",
      "↳ Make the bot send a message in a channel",
      "",
      "`#announce <title> | <body>` / `/announce`",
      "↳ Post a formatted announcement embed",
      "",
      "`#dm @user <message>` / `/dm`",
      "↳ Send a private DM to a user from the bot",
      "",
      "`#chat @user [message]` / `/chat`",
      "↳ Open a DM relay — their replies appear in the log channel",
      "",
      "`#reply @user <message>` / `/reply`",
      "↳ Reply to a user in an active DM relay",
      "",
      "`#ping` / `/ping`",
      "↳ Check bot latency in milliseconds",
      "",
      "`#userinfo [@user]` / `/userinfo`",
      "↳ Show info about a user — joined date, roles, and more",
      "",
      "`#avatar [@user]` / `/avatar`",
      "↳ Show a user's full-size avatar",
      "",
      "`#banner [@user]` / `/banner`",
      "↳ Show a user's profile banner",
      "",
      "`#serverinfo` / `/serverinfo`",
      "↳ Show server stats — members, roles, channels, and more",
      "",
      "`#servericon` / `/servericon`",
      "↳ Show the server's icon in full size",
      "",
      "`#roleinfo @role` / `/roleinfo`",
      "↳ Show detailed info about a role",
      "",
      "`#channelinfo [#channel]` / `/channelinfo`",
      "↳ Show info about a channel",
      "",
      "`#emoji <emoji>` / `/emoji`",
      "↳ Show info about a custom emoji",
      "",
      "`#listbans` / `/listbans`",
      "↳ List all banned users",
      "",
      "`#listroles` / `/listroles`",
      "↳ List all roles in the server",
      "",
      "`#listchannels` / `/listchannels`",
      "↳ List all channels in the server",
      "",
      "`#listmembers` / `/listmembers`",
      "↳ List all members in the server",
    ].join("\n"),
  },
];

export const TOTAL_PAGES = PAGES.length;

export function buildHelpEmbed(page: number): EmbedBuilder {
  const p = PAGES[page];
  return new EmbedBuilder()
    .setColor(p.color)
    .setTitle(`🚔 LGENDARY POLICE OFFICER — Help (${page + 1}/${TOTAL_PAGES})`)
    .setDescription(p.title + "\n\n" + p.fields)
    .setFooter({ text: `Page ${page + 1} of ${TOTAL_PAGES} • All commands require Admin` });
}

export function buildHelpRow(page: number, userId: string): ActionRowBuilder<ButtonBuilder> {
  return new ActionRowBuilder<ButtonBuilder>().addComponents(
    new ButtonBuilder()
      .setCustomId(`hp:p:${page}:${userId}`)
      .setLabel("◀ Prev")
      .setStyle(ButtonStyle.Secondary)
      .setDisabled(page === 0),
    new ButtonBuilder()
      .setCustomId(`hp:info:${page}:${userId}`)
      .setLabel(`Page ${page + 1} / ${TOTAL_PAGES}`)
      .setStyle(ButtonStyle.Primary)
      .setDisabled(true),
    new ButtonBuilder()
      .setCustomId(`hp:n:${page}:${userId}`)
      .setLabel("Next ▶")
      .setStyle(ButtonStyle.Secondary)
      .setDisabled(page === TOTAL_PAGES - 1),
  );
}
